name: 每日定时任务Demo

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run‑demo:
    runs‑on: ubuntu‑latest
    steps:
      - name: 下载仓库代码
        uses: actions/checkout@v4

      - name: 运行脚本，写入日志
        run: |
          echo "任务执行完成，时间: $(date)" >> log.txt

      - name: 提交保存日志文件
        run: |
          git config --global user.name "song95596-调试"
          git config --global user.email "song95596@gmail"
          git add log.txt
          git commit -m "自动更新日志 $(date)"
          git push
